Fixed responsiveness and updated Tech Secy info
KamandPrompt/sntc pull request #27
Opened 2020-10-03 01:51 UTC by divyashk

### 1.Updated Tech Secy info
### 2.The "flex-wrap" for "services available" on the services page was not set to "wrap". The css was using media query to convert it into a single column which wasted a lot of space on the page.
### 3.The tech secy photo was of a constant width which broke the layout below 600 px. Also the email was too long, so it broke out of the div on smaller screens. 

## Before
![Screenshot from 2020-10-03 07-08-39](https://user-images.githubusercontent.com/53950730/94980565-83166800-0548-11eb-87a2-e7f2827116d4.png)
## After
![Screenshot from 2020-10-03 07-08-57](https://user-images.githubusercontent.com/53950730/94980566-84e02b80-0548-11eb-948f-15b5dbf6c3e3.png)

## Before
![Screenshot from 2020-10-03 07-09-32](https://user-images.githubusercontent.com/53950730/94980567-86115880-0548-11eb-864f-7ac0947be110.png)
#After
![Screenshot from 2020-10-03 07-09-56](https://user-images.githubusercontent.com/53950730/94980569-86a9ef00-0548-11eb-97b5-337afd53bf30.png)

2020-10-12 12:22 UTC, vsvipul commented
@kartik1000  please test and merge  asap.

2020-10-12 16:43 UTC, LalitNM requested changes
Because you have changed responsiveness of the page, now this creates an additional problem of responsiveness of system admins page. I am adding before and after screenshot. You need to rectify this.

Before:
![image](https://user-images.githubusercontent.com/63332774/95771053-ee2f0f80-0ca9-11eb-896f-a91a03b2b4a0.png)

After: 
![image](https://user-images.githubusercontent.com/63332774/95771070-f5561d80-0ca9-11eb-9796-70ee4f75bc80.png)

2020-10-12 18:55 UTC, divyashk commented
@LalitNM That was caused because we are using the same CSS file for two different html pages.

2020-10-13 07:09 UTC, divyashk commented
@LalitNM  The font size was causing the problem. It is fixed now.
![Screenshot from 2020-10-13 12-35-20](https://user-images.githubusercontent.com/53950730/95826871-97c8dc00-0d50-11eb-96a3-e237bac69c5c.png)
![Screenshot from 2020-10-13 12-36-47](https://user-images.githubusercontent.com/53950730/95827017-d52d6980-0d50-11eb-8a33-a278e7a3c38d.png)
![Screenshot from 2020-10-13 12-37-02](https://user-images.githubusercontent.com/53950730/95827026-d65e9680-0d50-11eb-9644-bd4ed455b44f.png)

2020-10-13 09:27 UTC, vsvipul commented
@LalitNM  can you review again ? also @kartik1000  have a look.

2020-10-13 11:43 UTC, Ruchika06 reviewed
The vertical width aligns correctly
Create a pr by creating a new local checkout branch other than master next time:)

2020-10-13 11:48 UTC, kartik1000 approved these changes
The changes look good to me overall. @Ruchika06 if you are also satisfied please merge this.

2020-10-13 11:49 UTC, divyashk commented
> The vertical width aligns correctly
> Create a pr by creating a new local checkout branch other than master next time:)

Yeah sure, will do from now on, didn't know that before.

2020-10-13 11:49 UTC, LalitNM commented
Yeah, looks good.

2020-10-13 11:53 UTC, merged